cameri/nostream

- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
1. Add PR template
2. Add CONTRIBUTING.md
1. Add documentation to incentivize contributions
> Add PR template & contributing doc

- src/@types/adapters.ts
- src/@types/messages.ts
- src/adapters/web-socket-adapter.ts
- src/handlers/subscribe-message-handler.ts
- test/unit/handlers/subscribe-message-handler.spec.ts
1. Add unit tests to SubscribeMessageHandler
Part of https://github.com/Cameri/nostr-ts-relay/issues/3
- Increase unit test coverage to above 80%
1. Unit tests
> test: add unit tests for SubscribeMessageHandler

- CONFIGURATION.md
- README.md
- settings.sample.json
1. Document the environment variables and settings file
https://github.com/Cameri/nostr-ts-relay/issues/19
Without proper documentation, someone looking to run `nostr-ts-relay` would need to look in the code to understand what the different environment variables and settings are and their purpose.
Testing not needed.
> doc: add CONFIGURATION.md

- .github/workflows/checks.yml
- docker-compose.yml
- package.json
- test/integration/docker-compose.yml
- test/integration/features/shared.ts
1. Set PORT environment variable so integration tests can connect to the relay under test
https://github.com/Cameri/nostr-ts-relay/issues/3
1. SERVER_PORT was renamed to PORT which caused integration tests to fail. Unsure why CI did not catch this.
1. Ran integration and coverage tests locally.
> fix: integration tests failing

- CONFIGURATION.md
- README.md
- docker-compose.tor.yml
- docker-compose.yml
- scripts/start_with_tor
- settings.sample.json
- src/@types/settings.ts
- src/adapters/web-server-adapter.ts
- src/adapters/web-socket-adapter.ts
- src/app/worker.ts
- src/factories/worker-factory.ts
- src/handlers/delegated-event-message-handler.ts
- src/handlers/event-message-handler.ts
- src/handlers/event-strategies/delete-event-strategy.ts
- src/handlers/event-strategies/ephemeral-event-strategy.ts
- src/handlers/event-strategies/parameterized-replaceable-event-strategy.ts
- src/handlers/event-strategies/replaceable-event-strategy.ts
- src/handlers/subscribe-message-handler.ts
- src/handlers/unsubscribe-message-handler.ts
1. Prevents DoS attack when receiving a large payload over websockets
2. Add Redis env vars to `CONFIGURATION.md`
3. Add network.max_payload_size to settings and to `CONFIGURATION.md`
4. Add network.remote_ip_header to settings and to `CONFIGURATION.md`
5. Add warning about using non-official Docker distributions.
6. Fix Tor docker compose mounting wrong data folder
7. Reduce logging causing disk to be filled
8. Fix incorrent HTTP header being sent for non-WS requests
9. Fix issue regarding too many event listeners when receiving many subscriptions in rapid succession
10. Log WebSocket errors properly
11. Destroy find event query stream instead of ending the stream abruptly to release connection
https://github.com/Cameri/nostr-ts-relay/issues/95
1. Improve stability
2. Allow more …
> fix: error max payload size exceeded

- src/schemas/base-schema.ts
- src/schemas/event-schema.ts
- src/schemas/filter-schema.ts
- test/unit/schemas/event-schema.spec.ts
- test/unit/schemas/filter-schema.spec.ts
Signed-off-by: Ricardo Arturo Cabral Mejía <me@ricardocabral.io>
1. Reject subscriptions with unsafe integers in since/until 
https://github.com/Cameri/nostream/issues/110
1. Unsafe integers cause errors when querying the database
1. Unit tests
> fix: reject sub with unsafe ints in since/until

- .nostr.local/certs/.gitignore
- .nostr.local/settings.json
- Caddyfile.local
- README.md
- docker-compose.local.yml
- scripts/start_local
Includes locally-trusted TLS certs via mkcert and uses a hostname that already points to 127.0.0.1 without having to modify the hosts file.
This change makes it easy to spin up a local environment for development, both for enhancements to the relay and for use while developing a nostr client. It uses [Caddy](https://caddyserver.com/) as the reverse-proxy, [mkcert](https://github.com/FiloSottile/mkcert) to generate certs for the hostname that are trusted on the developer's machine, and a [localtest.me](https://readme.localtest.me/) subdomain for the hostname to avoid requiring a change to the machine's host file.
#117
Quickly overcomes the barrier to getting the relay working in a local environment. Anything that makes the relay easier to use will help boost adoption and contributions to …
> Add reverse proxy for local dev

- CONFIGURATION.md
- docker-compose.yml
- src/app/worker.ts
- src/database/client.ts
- src/handlers/subscribe-message-handler.ts
1. Fixes #140 
1. Under load, Nostream takes a little longer to acquire a new connection, in some cases it is unable to acquire and an error is thrown causing the worker to crash. All clients connected to the worker would lose connection.
1. Lowered acquireConnectionTimeout in order to replicate the issue
2. Ran Nostream and conducted requests and sent events
> fix: bug typeerror cannot read properties of undefined reading   knexuid

- src/app/app.ts
- src/utils/settings.ts
- test/integration/features/shared.ts
This patch fixes scenarios where the user renamed the settings file to `settings.json.<something>` which caused the settings setup script to concatenate the settings name incorrectly
N/A
Fixes a bug
Local reproduction of issue
Update of a method, no backward compatiblity implications
- [] My change requires a change to the documentation.
> fix: SettingsStatic class default to yaml file

- README.md
- I had to set `DB_USER` seperately for the DB migrations to run.
- I had to copy over the `settings.yaml` file because it wasn't created by default.
> Fix instructions to run locally

- src/repositories/event-repository.ts
https://github.com/Cameri/nostream/issues/206
> fix: don't send expiration data to buff

- README.md
Minor update to README for UX. 
Adding a `NODE_OPTIONS` preface to the command to pre-load dotenv
When a user specifies custom database parameters in `.env`, these are not currently loaded during an `npm run db:migrate`. Pre-loading dotenv through the `NODE_OPTIONS` is a low-lift one-line option to assist someone walking step-by-step through the instructions.
Personal experience:)
> Pre-load dotenv to properly load db env variables

- migrations/20230205_004400_change_invoice_id_to_string.js
- migrations/20230217_235600_scale_balance_addition_with_unit.js
- resources/default-settings.yaml
- src/@types/invoice.ts
- src/@types/settings.ts
- src/app/app.ts
- src/constants/base.ts
- src/controllers/callbacks/lnbits-callback-controller.ts
- src/controllers/invoices/post-invoice-controller.ts
- src/factories/lnbits-callback-controller-factory.ts
- src/factories/maintenance-worker-factory.ts
- src/factories/payments-processor-factory.ts
- src/factories/post-invoice-controller-factory.ts
- src/factories/zebedee-callback-controller-factory.ts
- src/handlers/request-handlers/post-lnbits-callback-request-handler.ts
- src/payments-processors/lnbits-payment-processor.ts
- src/routes/callbacks/index.ts
- src/services/payments-service.ts
- src/utils/event.ts
- src/utils/secret.ts
Adds the LNbits payment processor. Also includes:
- small refactoring changes
- `BigInt` -> `bigint` on files that I have touched
- use utility functions to create PaymentsServices instead of manually doing it
- migration to switch invoice IDs to TEXT
- callback refactoring
Closes #163
Allowing users to receive pay to relay payments via alternative methods/to their own node.
Tested on production with atlas.nostr.land. Would prefer someone else tests this too.
note: I couldn't find any tests related to pay to relay
> Add LNbits payment processor

- docker-compose.yml
- resources/default-settings.yaml
- src/adapters/web-socket-adapter.ts
- src/app/app.ts
- src/factories/worker-factory.ts
> fix: rsv1 error

- resources/default-settings.yaml
- resources/invoices.html
- src/@types/base.ts
- src/@types/services.ts
- src/@types/settings.ts
- src/app/maintenance-worker.ts
- src/constants/base.ts
- src/controllers/invoices/post-invoice-controller.ts
- src/handlers/event-message-handler.ts
- src/handlers/request-handlers/root-request-handler.ts
- src/handlers/subscribe-message-handler.ts
- src/payments-processors/lnurl-payments-processor.ts
- src/schemas/base-schema.ts
- src/schemas/event-schema.ts
- src/schemas/filter-schema.ts
- src/services/payments-service.ts
- src/utils/event.ts
- src/utils/secret.ts
- src/utils/sliding-window-rate-limiter.ts
- test/integration/features/helpers.ts
- test/integration/features/nip-01/nip-01.feature
- test/integration/features/nip-16/nip-16.feature
- test/integration/features/shared.ts
- test/unit/handlers/delegated-event-message-handler.spec.ts
- test/unit/handlers/event-message-handler.spec.ts
- test/unit/repositories/event-repository.spec.ts
- test/unit/schemas/event-schema.spec.ts
- test/unit/schemas/filter-schema.spec.ts
> fix: issues with invoices

- scripts/start
- scripts/start_local
- scripts/start_with_tor
Added a check to the start scripts to ensure they are being run from the correct directory. Informs user if they're being run from /scripts/ directly and provides a descriptive error message.
Fixes #218
If the start script(s) are run from the incorrect directory this currently throws a confusing error message.
This fix checks the directory the script is being run from and will alert the user if they're running it from the wrong directory.
#218 
I encountered this problem myself when testing Nostream, and found an issue had already been raised, so I assume others will be making the same mistake and assuming it's "safe" to run ./start from within the scripts folder.  Adding a simple message to the script will save people time troubleshooting postgres errors.
Tested on Ubuntu Server 22.04
- …
> Added directory check to start scripts

- src/adapters/web-socket-adapter.ts
If the SECRET env var isn't set, the error emitted from event-message-handler gets swallowed.
- [-] My change requires a change to the documentation.
- [-] I have updated the documentation accordingly.
- [-] I have added tests to cover my code changes.
> Avoid swallowing errors in web-socket-adapter

- README.md
- docker-compose.yml
This might close #284
The `SECRET` env variable is mandatory by now, but the README and the `docker-compose.yml` don't reflect this.
People running the service as docker will run into the following error: 
`web-socket-adapter: unable to handle message: Error: SECRET environment variable not set`
This can be fixed setting up a secret and providing it via a `.env` file in the `docker-compose.yml`.
#284 
see description
I tested it with my own relay.
Before I was not able to send events. I did get no error message, but no success or "OK" response as well.
Now I am.
> fix: add SECRET as env variable to docker-compose setup

- resources/default-settings.yaml
1. Add `mailto:` URI scheme to `info.contact` in default-settings.yaml
https://github.com/Cameri/nostream/issues/299
> chore: use mailto: scheme for info.contact in settings

- CONFIGURATION.md
- docker-compose.yml
- resources/default-settings.yaml
- src/@types/settings.ts
- src/constants/base.ts
- src/handlers/event-message-handler.ts
- test/unit/handlers/event-message-handler.spec.ts
1. Allow event kinds to be waived for admission fee
https://github.com/Cameri/nostream/issues/302
1. Allow LN wallet providers to publish zaps to paid relays
> 302 request allow lightning zap receipts on paid relays

- src/utils/filter.ts
- test/unit/utils/filter.ts
Allow generic tag queries to be in uppercase.
https://github.com/Cameri/nostream/issues/311
NIP-12 does not mention tags should be lowercase, meaning uppercase letters should also be allowed.
> fix: generic tag queries not accepting uppercase letters

- src/controllers/callbacks/zebedee-callback-controller.ts
1. Fix Zebedee callback incorrectly passing confirmedAt when confirming invoice
https://github.com/Cameri/nostream/issues/317
1. Nostream v1.25.0 with zebedee as payments processor fails to confirm invoice
> fix: zebedee callback not marking invoice as paid

- src/@types/services.ts
- src/controllers/callbacks/opennode-callback-controller.ts
- src/controllers/callbacks/zebedee-callback-controller.ts
1. Confirming invoice no longer fails because of missing data
https://github.com/Cameri/nostream/issues/319
> fix: confirm invoice missing params

- src/controllers/invoices/get-invoice-status-controller.ts
- src/handlers/event-message-handler.ts
- src/repositories/event-repository.ts
- src/utils/event.ts
- test/integration/features/nip-16/nip-16.feature
- test/integration/features/nip-33/nip-33.feature
- test/integration/features/nip-33/nip-33.feature.ts
- test/integration/features/shared.ts
https://github.com/Cameri/nostream/issues/255
> fix: strange behavior with nip 33 parameterized replacable events and nip 40 expiration tag

- migrations/20240108_130100_add_event_tags_table.js
- src/repositories/event-repository.ts
- test/unit/repositories/event-repository.spec.ts
This pull request introduces a new `event_tags` table and its associated migration script. By expanding and indexing the contents of the tags field of the events table in the events_tags table in advance, the search process by REQ can be made much faster than the original JSONB operation.
[#348](https://github.com/Cameri/nostream/issues/348) 
The addition of the `event_tags` table is required to efficiently manage and query event tag data. This change aims to improve data organization and access, facilitating better event management within the application.
The changes have been tested in a local development environment. I performed the following tests:
- Successfully ran the migration script to create the `event_tags` table.
- Inserted sample data into the `event_tags` table and verified …
> feat(event_tags): Add event_tags table and migration script

- src/handlers/request-handlers/nodeinfo-handler.ts
- src/routes/index.ts
Adds support for [nodeinfo](https://github.com/jhass/nodeinfo) a standard of decentralized social networks. It will allow nostream relays to be indexed on sites like [FediDB](https://fedidb.org/) by adhering to a common format of decentralized networks of the past. It's similar in concept to nip11 but for more general use across different protocols.
I didn't open an issue first, my mistake.
It will open doors to greater interoperability between decentralized protocols.
I ran it in the local Docker environment and it works.
> feat: add nodeinfo support

- src/@types/repositories.ts
- src/handlers/event-strategies/delete-event-strategy.ts
- src/repositories/event-repository.ts
- test/integration/features/nip-09/nip-09.feature
- test/integration/features/nip-33/nip-33.feature
- test/integration/features/nip-33/nip-33.feature.ts
- test/unit/handlers/event-strategies/delete-event-strategy.spec.ts
- test/unit/repositories/event-repository.spec.ts
Fixes an error when an delete event is received before the parameterized replaceable event and the parameterized replaceable event causes an error.
https://github.com/Cameri/nostream/issues/343
1. Unit tests
2. Integration tests
> fix: deleting parameterized replaceable event before event

- src/handlers/request-handlers/root-request-handler.ts
1. Parse npubs from info.pubkey from bech32 to hex for the NIP-11 document
https://github.com/Cameri/nostream/issues/331
Mike Dilger asked for it.
With `curl -H 'Accept: application/nostr+json' http://127.0.0.1:8008/`
> chore: convert info.pubkey from bech32 to hex for nip-11

- resources/css/style.css
- resources/index.html
- resources/invoices.html
- resources/terms.html
- Add dark theme CSS code in styling file.
- Add a script to detect preferred color scheme on page `index.html`, `invoices.html` and `terms.html`.
> feat: add dark theme support for static html files

- CONFIGURATION.md
Adding one line to explain that `nostream` will dynamically pick up any changes to the `settings.yaml` file.
Not an issue, just trying to help inform others who might have the same question.
> docs: add note to configration readme
