README.md
migrations/20221030_134400_add_deduplication_to_events_table.js
migrations/20221030_134500_add_dedulication_to_replaceable_events_unique_index.js
package-lock.json
package.json
src/@types/event.ts
src/constants/base.ts
src/factories/event-strategy-factory.ts
src/handlers/event-strategies/parameterized-replaceable-event-strategy.ts
src/repositories/event-repository.ts
src/utils/event.ts
test/integration/features/helpers.ts
test/integration/features/nip-01/nip-01.feature.ts
test/integration/features/nip-33/nip-33.feature
test/integration/features/nip-33/nip-33.feature.ts
test/integration/features/shared.ts
test/unit/repositories/event-repository.spec.ts
test/unit/utils/event.spec.ts

1. Adds supports for [NIP-33 Parameterized Replaceable Events](https://github.com/nostr-protocol/nips/pull/54)
https://github.com/Cameri/nostr-ts-relay/issues/29
1. Support NIP-33

29 support nip 33 parameterized replaceable events

---

.github/workflows/release.yml
.releaserc.json
package-lock.json
package.json

Add semantic releases.
Add semantic releases.
https://github.com/Cameri/nostr-ts-relay/issues/21
1. Automatically release new version on deploy

chore(ci): add semantic releases

---

.github/workflows/checks.yml
.github/workflows/release.yml
.releaserc.json
package-lock.json
package.json

chore: add tg bot

---

.github/workflows/checks.yml
README.md
package.json

fix: github checks workflow 

---

CONFIGURATION.md
Dockerfile.railwayapp
README.md
src/app/worker.ts

This adds support to one of many deployment services like Railway App , it is quite simple and lets you run easily without complexity.
#27 
I think this would help people to quickly spin relay easily rather then running locally and in production without worrying about this and that.
Yeah , this has been tested, I have tested the deployment at my end.

Railway App Support

---

.github/workflows/checks.yml
.github/workflows/release.yml
docker-compose.yml

1. Deploy after release
https://github.com/Cameri/nostr-ts-relay/issues/42
1. Manually deploying nostr-ts-relay is a chore. This PR automates that process so that nostr-relay.wlvs.space is running the latest version.
1. Manually

chore(ci): deploy after release

---

CONFIGURATION.md
docker-compose.yml
settings.sample.json
src/@types/adapters.ts
src/@types/settings.ts
src/adapters/web-socket-adapter.ts
src/database/client.ts
src/handlers/event-message-handler.ts
test/unit/handlers/event-message-handler.spec.ts

1. Fixes the issue of dropping events due to being unable to process events

Fix: Running out of DB connections

---

src/schemas/filter-schema.ts
test/unit/schemas/filter-schema.spec.ts

Signed-off-by: Ricardo Arturo Cabral Mejía <me@ricardocabral.io>

chore: allow filter with limit zero

---

package-lock.json
package.json

1. Add sinon as dev dependency
https://github.com/Cameri/nostream/issues/112
1. Unable to run unit/integration tests if Sinon is missing.
1. Deleting node_modules and running `npm i`.
1. Running unit tests.
2.

fix: add sinon as dev dependency

---

src/adapters/web-socket-adapter.ts

Signed-off-by: Ricardo Arturo Cabral Mejía <me@ricardocabral.io>
1. Relay replies with a NOTICE when receiving malformed input
https://github.com/Cameri/nostream/issues/109
1. Malformed messages were logged to console but not informed to client
1. Manually

fix: handle malformed incoming messages

---

package-lock.json
package.json
src/index.ts

feat: add support to dotenv files

---

Dockerfile
docker-compose.yml
package-lock.json
package.json
src/@types/tor.ts
src/app/app.ts
src/tor/client.ts
test/unit/tor/onion.spec.ts

feat: automatic onion services

---

CONFIGURATION.md

docs: :memo: documented new environment var

---

CONFIGURATION.md
README.md
knexfile.js
src/cache/client.ts
src/database/client.ts

Had issue with ssl certification on redis and postgresql. Having a connection URI will remove the need to manually change the URI in code.

feat: added uri string for redis and postgres

---

README.md

Forgot to add NIP-40 to readme

fix: update supported nips in readme

---

README.md

As requested by @Cameri adding the guide + contrib name

Adding Paid Nostr Relay Guide + Andre Contrib

---

src/factories/web-app-factory.ts
src/routes/index.ts

#182 
#182 
Calling `curl http://127.0.0.1:8008/healthz` many times.

chore: disable /healthz rate limit

---

knexfile.js
resources/default-settings.yaml
src/controllers/callbacks/zebedee-callback-controller.ts
src/controllers/invoices/post-invoice-controller.ts

fix: bug unable confirm invoice

---

CONFIGURATION.md
README.md
docker-compose.yml
migrations/20230220_002700_fix_unit_confirm_invoice_func.js
package-lock.json
package.json
resources/default-settings.yaml
resources/invoices.html
scripts/start_local
src/app/app.ts
src/controllers/invoices/get-invoice-status-controller.ts
src/factories/payments-processor-factory.ts
src/factories/web-app-factory.ts
src/handlers/request-handlers/post-invoice-request-handler.ts
src/handlers/request-handlers/root-request-handler.ts
src/routes/invoices/index.ts

fix: confirm invoice function ambiguous unit variable

---

README.md

Cleaning up the docs / readme related to ZEBEDEE API integration
- refactor: cleanup URL + readme docs for ZEBEDEE API integration with Nostream
https://github.com/Cameri/nostream/issues/307
Want to ensure Nostream operators have all the context on how to best setup/run their paid relays
By the ZEBEDEE eng team.

ZEBEDEE API documentation / readme cleanup

---

README.md

Add lnbits configuration in readme

docs: add lnbits in readme

---

README.md

Adds lnurl configuration in readme

docs: add lnurl in readme

---

src/services/payments-service.ts

lnurl payment processor, cannot be found when looking for invoice
an error occurred while debugging lnurl payment

fix: `invoice.verifyURL` undefined from lnurl processor getInvoice

---

package-lock.json
package.json

Update Axios to 1.6.5.
None
Address security issue.
It wasn't. We are hoping for the best.

chore: bump axios to 1.6.5

---

package-lock.json
package.json

chore: update @cucumber/cucumber to 10.2.1
